# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce3d494472b5ab38a52e7ca6612ea2583de4fe1b93e3a6c2289e5c7df66923dc4825279bbb64bd8ebf1056f67450fa8e20da07b8d8984fb130de5827247f8c85

test:
  secret_key_base: 8fcf17f3af998da84a0ec5122d87008d6370c104d54205052b1a22ea2c08e8c645ad873f5a22a299ed9d3fabf5e102c07f66ff63da6b6cbdd8f33e6733fcbea2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
